name: test by jest

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.1
        cache: npm

    - name: Npm install
      run: npm i jest --quiet
      shell: bash

    - name: Testing By Jest
      run: npm run test:build
      shell: bash
